USER_SEEDS = [
    {
        "username": "rionaldus",
        "password": "rionaldus123",
        "name": "Rionaldus S",
        "email": "rionaldus@atl.local",
        "nip": "19901112 201502 1 003",
        "roleLabel": "ATL Expert",
        "roleGroup": "ATL Expert",
        "status": "Aktif",
        "lastLogin": "Seed account",
        "classAccess": ["3A", "4A"],
        "subjectAccess": ["singing", "ipa", "math"],
        "isStaff": True,
    },
    {
        "username": "akademik",
        "password": "akademik123",
        "name": "Maria Ulfa Rahmawati",
        "email": "akademik@atl.local",
        "nip": "19890214 201103 2 011",
        "roleLabel": "Akademik",
        "roleGroup": "Akademik",
        "status": "Aktif",
        "lastLogin": "Seed account",
        "classAccess": ["3A", "4A"],
        "subjectAccess": [],
        "isStaff": True,
    },
    {
        "username": "wali3a",
        "password": "wali12345",
        "name": "Megawati Putri",
        "email": "wali3a@atl.local",
        "nip": "19850325 201001 2 001",
        "roleLabel": "Guru (Wali Kelas)",
        "roleGroup": "Guru Wali Kelas",
        "status": "Aktif",
        "lastLogin": "Seed account",
        "classAccess": ["3A"],
        "subjectAccess": [],
    },
    {
        "username": "ipa",
        "password": "ipa12345",
        "name": "Joko Wiryanto",
        "email": "ipa@atl.local",
        "nip": "19920505 201801 2 005",
        "roleLabel": "PJ Mapel - IPA",
        "roleGroup": "PJ Mapel",
        "status": "Aktif",
        "lastLogin": "Seed account",
        "classAccess": ["3A", "4A"],
        "subjectAccess": ["ipa"],
    },
    {
        "username": "math",
        "password": "math12345",
        "name": "Andi Prasetyo",
        "email": "math@atl.local",
        "nip": "19930809 201909 1 007",
        "roleLabel": "PJ Mapel - Math",
        "roleGroup": "PJ Mapel",
        "status": "Aktif",
        "lastLogin": "Seed account",
        "classAccess": ["4A"],
        "subjectAccess": ["math"],
    },
    {
        "username": "admin",
        "password": "admin12345",
        "name": "Afrizal Haykal",
        "email": "admin@atl.local",
        "nip": "",
        "roleLabel": "Admin",
        "roleGroup": "Admin",
        "status": "Aktif",
        "lastLogin": "Seed account",
        "classAccess": [],
        "subjectAccess": [],
        "isStaff": True,
        "isSuperuser": True,
    },
]

EXTRA_TOPICS = {
    "singing": [
        {"id": "singing_music_theory_basics", "label": "Music Theory Basics", "description": "Dasar teori musik"},
        {"id": "singing_performance_practice", "label": "Performance Practice", "description": "Latihan performa musik"},
    ],
    "ipa": [
        {"id": "ipa_ekosistem", "label": "Ekosistem", "description": "Relasi makhluk hidup dan lingkungan"},
    ],
    "math": [
        {"id": "math_quadratic_functions", "label": "Quadratic Functions", "description": "Fungsi kuadrat"},
        {"id": "math_trigonometry", "label": "Trigonometry", "description": "Trigonometri dasar"},
    ],
}

TOPIC_RUBRICS = {
    "singing_christmas_carol": [
        {
            "topic": "Creating",
            "title": "Role Play & Musical Contribution",
            "categories": ["Social Skills"],
            "subskills": ["Interpersonal relationships", "Social-emotional intelligence"],
            "levels": {
                "NFI": "Fails to participate in the assigned part.",
                "PTE": "Significantly struggles with assigned role; negatively impacts the group.",
                "DE": "Tries to fulfill role; struggles with technical requirements.",
                "ME": "Executes assigned role effectively; contributes reliably to the music.",
                "EE": "Skillfully executes role; demonstrates high technical command.",
            },
        },
        {
            "topic": "Creating",
            "title": "Rhythm & Tempo Accuracy",
            "categories": ["Thinking Skills"],
            "subskills": ["InformationTransfer", "Reflection / Metacognitive", "Critical Thingking"],
            "levels": {
                "NFI": "Cannot follow the rhythm or tempo.",
                "PTE": "Difficulty maintaining tempo.",
                "DE": "Often out of sync with the music's tempo.",
                "ME": "Performs with mostly accurate rhythm.",
                "EE": "Performs with highly accurate rhythm.",
            },
        },
        {
            "topic": "Creating",
            "title": "Ensemble Balance & Dynamics",
            "categories": ["Social Skills"],
            "subskills": ["Interpersonal relationships", "Social-emotional intelligence"],
            "levels": {
                "NFI": "No awareness of group sound or control.",
                "PTE": "Difficulty controlling volume.",
                "DE": "Volume is sometimes unbalanced.",
                "ME": "Maintains balanced ensemble contribution.",
                "EE": "Shows highly polished ensemble balance.",
            },
        },
        {
            "topic": "Responding",
            "title": "Focus & Attention",
            "categories": ["Self-Management Skills"],
            "subskills": ["State of Mind", "Organization skills"],
            "levels": {
                "NFI": "Does not show attention to the lesson at all.",
                "PTE": "Is often unfocused and distracts others.",
                "DE": "Is sometimes attentive, but is often distracted by others.",
                "ME": "Pays attention to teacher and peer instructions well.",
                "EE": "Always pays attention to teacher and peer instructions.",
            },
        },
        {
            "topic": "Responding",
            "title": "Participation & Effort",
            "categories": ["Self-Management Skills"],
            "subskills": ["State of Mind"],
            "levels": {
                "NFI": "Is completely unwilling to participate in music activities in class.",
                "PTE": "Often refuses to participate in singing or practice activities.",
                "DE": "Participates when asked or encouraged by the teacher.",
                "ME": "Actively participates in most activities.",
                "EE": "Very enthusiastic and always actively participates in all music activities.",
            },
        },
        {
            "topic": "Responding",
            "title": "Responsibility & Respect",
            "categories": ["Social Skills"],
            "subskills": ["Social-emotional intelligence", "Interpersonal relationships"],
            "levels": {
                "NFI": "Shows a lack of concern for classroom rules, peers, and the teacher.",
                "PTE": "Needs repeated reminders to be respectful.",
                "DE": "Sometimes forgets classroom rules.",
                "ME": "Shows respect for the teacher and peers.",
                "EE": "Listens respectfully when others are performing or the teacher is speaking.",
            },
        },
    ],
    "singing_choir": [
        {
            "topic": "Choir Performance",
            "title": "Harmonization Accuracy",
            "categories": ["Research Skills"],
            "subskills": ["Media Literacy", "Textual Literacy"],
            "levels": {
                "NFI": "Cannot identify when harmony is out of tune or disconnected from the group.",
                "PTE": "Frequently loses pitch and needs repeated support to rejoin the harmony.",
                "DE": "Maintains some harmony, but pitch and blend shift during difficult transitions.",
                "ME": "Blends with the group and keeps harmony stable with minor pitch issues.",
                "EE": "Maintains accurate harmony, adjusts independently, and strengthens the group sound.",
            },
        },
        {
            "topic": "Choir Performance",
            "title": "Performance Expression",
            "categories": ["Communication Skills"],
            "subskills": ["Exchanging Information", "Literacy skills"],
            "levels": {
                "NFI": "Sings without clear expression, phrasing, or attention to musical meaning.",
                "PTE": "Shows limited expression and rarely connects expression to the song text.",
                "DE": "Attempts expression, but phrasing and emotion are inconsistent.",
                "ME": "Communicates the song clearly with appropriate expression and phrasing.",
                "EE": "Uses expressive phrasing, diction, and emotion to enhance the choir performance.",
            },
        },
        {
            "topic": "Choir Performance",
            "title": "Team Collaboration",
            "categories": ["Social Skills"],
            "subskills": ["Interpersonal relationships", "Social-emotional intelligence"],
            "levels": {
                "NFI": "Does not cooperate with the ensemble and disrupts rehearsal flow.",
                "PTE": "Participates inconsistently and needs reminders to listen to the group.",
                "DE": "Works with peers when prompted, but group awareness is uneven.",
                "ME": "Collaborates reliably and responds to group cues during rehearsal.",
                "EE": "Supports peers, listens actively, and helps the ensemble stay coordinated.",
            },
        },
    ],
    "singing_vocal_technique": [
        {
            "topic": "Vocal Technique",
            "title": "Breath Control",
            "categories": ["Self-Management Skills"],
            "subskills": ["State of Mind"],
            "levels": {
                "NFI": "Runs out of breath quickly and cannot complete short vocal phrases.",
                "PTE": "Needs frequent reminders to breathe before phrases and support the tone.",
                "DE": "Uses breath support sometimes, but control drops in longer phrases.",
                "ME": "Maintains steady breath support through most assigned vocal phrases.",
                "EE": "Uses controlled breathing to sing long phrases smoothly and confidently.",
            },
        },
        {
            "topic": "Vocal Technique",
            "title": "Pitch Accuracy",
            "categories": ["Thinking Skills"],
            "subskills": ["Critical Thingking"],
            "levels": {
                "NFI": "Cannot match the target pitch even with teacher modeling.",
                "PTE": "Matches pitch only occasionally and often drifts from the melody.",
                "DE": "Sings several notes correctly, but pitch accuracy is inconsistent.",
                "ME": "Keeps pitch mostly accurate across the assigned melody.",
                "EE": "Sings with accurate pitch and self-corrects quickly when needed.",
            },
        },
    ],
    "ipa_energi_perubahan": [
        {
            "topic": "Energy Investigation",
            "title": "Experiment Setup & Safety",
            "categories": ["Self-Management Skills"],
            "subskills": ["Organization skills"],
            "levels": {
                "NFI": "Cannot prepare materials safely or follow basic experiment rules.",
                "PTE": "Needs repeated reminders to use tools and materials safely.",
                "DE": "Sets up parts of the experiment with some safety reminders.",
                "ME": "Sets up the experiment correctly and follows safety expectations.",
                "EE": "Prepares materials independently and models safe procedures for peers.",
            },
        },
        {
            "topic": "Energy Investigation",
            "title": "Data Collection & Observation",
            "categories": ["Thinking Skills"],
            "subskills": ["Critical Thingking", "InformationTransfer"],
            "levels": {
                "NFI": "Does not record useful observations or measurable data.",
                "PTE": "Records incomplete data with frequent errors or missing details.",
                "DE": "Collects some relevant data, but observations need more precision.",
                "ME": "Collects mostly accurate data and records clear observations.",
                "EE": "Collects complete data and notices patterns or changes independently.",
            },
        },
        {
            "topic": "Energy Investigation",
            "title": "Collaboration & Communication",
            "categories": ["Communication Skills"],
            "subskills": ["Exchanging Information", "ICT skills"],
            "levels": {
                "NFI": "Does not contribute to the group investigation or discussion.",
                "PTE": "Shares little information and relies heavily on peers.",
                "DE": "Contributes when prompted, but explanations are still unclear.",
                "ME": "Participates actively and communicates observations clearly.",
                "EE": "Helps organize group discussion and explains scientific ideas clearly.",
            },
        },
        {
            "topic": "Energy Investigation",
            "title": "Problem-Solving / Critical Thinking",
            "categories": ["Thinking Skills"],
            "subskills": ["Critical Thingking", "InformationTransfer"],
            "levels": {
                "NFI": "Cannot suggest a solution when the investigation does not work.",
                "PTE": "Tries simple fixes but does not connect them to evidence.",
                "DE": "Suggests partial solutions using some evidence from the experiment.",
                "ME": "Uses evidence to solve most problems during the investigation.",
                "EE": "Analyzes problems carefully and proposes improvements based on evidence.",
            },
        },
    ],
    "ipa_tata_surya": [
        {
            "topic": "Solar System Inquiry",
            "title": "Planet Identification & Characteristics",
            "categories": ["Research Skills"],
            "subskills": ["Textual Literacy", "Media Literacy"],
            "levels": {
                "NFI": "Cannot identify planets or describe their main characteristics.",
                "PTE": "Identifies a few planets but gives unclear or inaccurate details.",
                "DE": "Identifies most planets with some confusion about characteristics.",
                "ME": "Accurately identifies planets and explains main characteristics.",
                "EE": "Gives detailed planet descriptions using accurate research information.",
            },
        },
        {
            "topic": "Solar System Inquiry",
            "title": "Scale Modeling Accuracy",
            "categories": ["Thinking Skills"],
            "subskills": ["Critical Thingking", "InformationTransfer"],
            "levels": {
                "NFI": "Does not attempt to represent relative size or distance.",
                "PTE": "Uses a model with major errors in size or distance.",
                "DE": "Shows some sense of scale, but several parts are inconsistent.",
                "ME": "Builds a mostly accurate model using appropriate relative scale.",
                "EE": "Creates a precise model and explains scale decisions clearly.",
            },
        },
        {
            "topic": "Solar System Inquiry",
            "title": "Collaborative Inquiry",
            "categories": ["Social Skills"],
            "subskills": ["Interpersonal relationships", "Social-emotional intelligence"],
            "levels": {
                "NFI": "Does not participate in group research or model creation.",
                "PTE": "Contributes minimally and waits for others to complete tasks.",
                "DE": "Contributes occasionally but needs prompting to stay involved.",
                "ME": "Works actively with peers and shares responsibilities fairly.",
                "EE": "Facilitates group work and helps peers resolve task challenges.",
            },
        },
    ],
    "ipa_sistem_tubuh": [
        {
            "topic": "Body System Inquiry",
            "title": "Concept Explanation",
            "categories": ["Communication Skills"],
            "subskills": ["Literacy skills"],
            "levels": {
                "NFI": "Cannot explain the body system or use relevant vocabulary.",
                "PTE": "Gives very limited explanations with frequent concept errors.",
                "DE": "Explains basic ideas but misses important relationships.",
                "ME": "Explains the body system clearly using appropriate vocabulary.",
                "EE": "Explains relationships within the body system with detail and clarity.",
            },
        },
    ],
    "math_linear_equations": [
        {
            "topic": "Linear Equations",
            "title": "Problem Translation",
            "categories": ["Thinking Skills"],
            "subskills": ["InformationTransfer"],
            "levels": {
                "NFI": "Cannot translate a word problem into a mathematical expression.",
                "PTE": "Identifies some numbers but forms an incorrect equation.",
                "DE": "Creates a partial equation with some missing relationships.",
                "ME": "Translates most word problems into correct linear equations.",
                "EE": "Translates problems accurately and explains the equation structure.",
            },
        },
    ],
    "math_geometry": [
        {
            "topic": "Geometry",
            "title": "Shape Reasoning",
            "categories": ["Thinking Skills"],
            "subskills": ["Critical Thingking", "Creative Thingking"],
            "levels": {
                "NFI": "Cannot identify shape properties or justify geometric choices.",
                "PTE": "Recognizes simple shapes but gives weak reasoning.",
                "DE": "Uses some properties to reason about shapes with support.",
                "ME": "Explains shape properties and solves most geometry tasks correctly.",
                "EE": "Applies shape properties flexibly and justifies solutions clearly.",
            },
        },
    ],
    "math_statistics": [
        {
            "topic": "Statistics",
            "title": "Data Interpretation",
            "categories": ["Thinking Skills"],
            "subskills": ["Critical Thingking", "InformationTransfer"],
            "levels": {
                "NFI": "Cannot read the data display or identify basic information.",
                "PTE": "Reads simple values but draws inaccurate conclusions.",
                "DE": "Interprets some data correctly with teacher support.",
                "ME": "Interprets data displays and explains reasonable conclusions.",
                "EE": "Compares data patterns and explains conclusions with strong evidence.",
            },
        },
    ],
}
